### ISSUE TITLE
Possible a bad value in gdpr.encryption. LETTERS_ALL

### ISSUE THREAD

**Issue by darekc7** [druids/django-GDPR#24]
In https://github.com/druids/django-GDPR/blob/master/gdpr/encryption.py#L17
there is
`LETTERS_ALL = LETTERS_ONLY + LETTERS_ONLY `
shouldn't be
`LETTERS_ALL = LETTERS_ONLY + LETTERS_UPPER `
?

**Comment by matllubos** [comment]
Thank you, I will check it

**Comment by matllubos** [comment]
https://github.com/druids/django-GDPR/pull/26
