### ISSUE TITLE
Models set to anonymise on delete, but model is not registered with gdpr-assist

### ISSUE THREAD

**Issue by arex18** [druids/django-GDPR#31]
**ValueError: Relationship 'X' set to anonymise on delete, but model is not registered with gdpr-assist.**

Python 3.7, Django 3.0.5

To register the model, docs specify to import gdpr_assist.admin.ModelAdmin, whereas if you look in the library this isn't included in the __init__.py file. Any resolutions?

**Comment by matllubos** [comment]
Sorry but we haven't tested it yet for django 3. Therefore django 3 is not supported now.

**Comment by arex18** [comment]
Thanks for the quick response. Closing.
